version: '3'

services:
  my-java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel_agency_spring_mvp_app
    image: travel_agency_spring_mvp_app:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data